# apiVersion: v1
# kind: ConfigMap
# metadata:
#    namespace: roboshop
#    name: frontend
#    labels:
#      component: frontend
#      project: roboshop
#      tier: web
# data:
#     REDIS_HOST= "redis" 
#     CATALOGUE_HOST= "catalogue" 
#     CATALOGUE_PORT= "8080"    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: frontend
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
   replicas: 1
   selector:
     matchLabels:
       component: frontend
       project: roboshop
       tier: web
   template:
      metadata:
        labels:
          component: frontend
          project: roboshop
          tier: web
      spec:
        containers:
        - name: frontend
          image: deena012/frontend:v1
        # envFrom:
        # - configMapRef:
        #     name: frontend  

---
apiVersion: v1
kind: Service
metadata:
   namespace: roboshop
   name: frontend
   labels:
     component: frontend
     project: roboshop
     tier: web
spec:
   selector:
     type: LoadBalancer
     component: frontend
     project: roboshop
     tier: web     
   ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
