apiVersion: v1
kind: ConfigMap
metadata:
   namespace: roboshop
   name: payment
   labels:
     component: payment
     project: roboshop
     tier: app
data:
    CART_HOST: "cart"
    CART_PORT: "8080"
    USER_HOST: "user"
    USER_PORT: "8080"
    AMQP_HOST: "rabbitmq" 
---
apiVersion: v1
kind: Secret
metadata:
  namespace: roboshop
  name: payment
  labels:
    component: payment
    project: roboshop
    tier: database
type: Opaque  
data:
   AMQP_user: "cm9ib3Nob3A="
   AMQP_PASS: "cm9ib3Nob3AxMjM="       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: payment
  labels:
    component: payment
    project: roboshop
    tier: app
spec:
   replicas: 1
   selector:
     matchLabels:
       component: payment
       project: roboshop
       tier: app
   template:
      metadata:
        labels:
          component: payment
          project: roboshop
          tier: app
      spec:
        containers:
        - name: payment
          image: deena012/payment:v1
          envFrom:
          - configMapRef:
              name: payment 
          - secretRef:
              name: payment     

---
apiVersion: v1
kind: Service
metadata:
   namespace: roboshop
   name: payment
   labels:
     component: payment
     project: roboshop
     tier: app
spec:
   selector:
     component: payment
     project: roboshop
     tier: app     
   ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080