apiVersion: v1
kind: Deployment
metadata:
   namespace: roboshop
   name: mongodb
   labels:
      component: mongodb
      project: roboshop
      tier: database
spec:
  replicas: 1
  selector:
     matchLabels:
       component: mongodb
       project: roboshop
       tier: database
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
     - name: mongodb 
       image: joindevops/mongodb:v1    
            
              