apiVersion: v1
kind: ConfigMap
metadata:
   namespace: roboshop
   name: user
   labels:
     component: user
     project: roboshop
     tier: app
data:
    MONGO: "true"
    MONGO_URL: "mongodb://mongodb:27017/user" 
    REDIS_URL: "redis://redis:6379"    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: user
  labels:
    component: user
    project: roboshop
    tier: app
spec:
   replicas: 1
   selector:
     matchLabels:
       component: user
       project: roboshop
       tier: app
   template:
      metadata:
        labels:
          component: user
          project: roboshop
          tier: app
      spec:
        containers:
        - name: user
          image: deena012/user:v1
          envFrom:
          - configMapRef:
              name: user  

---
apiVersion: v1
kind: Service
metadata:
   namespace: roboshop
   name: user
   labels:
     component: user
     project: roboshop
     tier: app
spec:
   selector:
     component: user
     project: roboshop
     tier: app     
   ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
